// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace turnos_back.Models
{
    public partial class SP_CONSULTAR_SERVICIOSResult
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public int costo { get; set; }
        public string enPromocion { get; set; }
    }
}
